/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author User
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setTitle("Menu");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jCadastroAmigo = new javax.swing.JMenuItem();
        jCadastroFerramenta = new javax.swing.JMenuItem();
        jCadastroEmprestimos = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jGerenciarAmigo = new javax.swing.JMenuItem();
        jGerenciarFerramenta = new javax.swing.JMenuItem();
        jGerenciarEmprestimo = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCadastro.setText("Cadastro");

        jCadastroAmigo.setText("Cadastrar Amigo");
        jCadastroAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroAmigoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jCadastroAmigo);

        jCadastroFerramenta.setText("Cadastrar Ferramenta");
        jCadastroFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroFerramentaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jCadastroFerramenta);

        jCadastroEmprestimos.setText("Cadastrar Empréstimo");
        jCadastroEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroEmprestimosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jCadastroEmprestimos);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuSair);

        jMenuBar2.add(jMenuCadastro);

        jMenu3.setText("Gerenciamento");

        jGerenciarAmigo.setText("Gerenciar Amigo");
        jGerenciarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGerenciarAmigoActionPerformed(evt);
            }
        });
        jMenu3.add(jGerenciarAmigo);

        jGerenciarFerramenta.setText("Gerenciar Ferramenta");
        jGerenciarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGerenciarFerramentaActionPerformed(evt);
            }
        });
        jMenu3.add(jGerenciarFerramenta);

        jGerenciarEmprestimo.setText("Gerenciar Empréstimo");
        jGerenciarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGerenciarEmprestimoActionPerformed(evt);
            }
        });
        jMenu3.add(jGerenciarEmprestimo);

        jMenuBar2.add(jMenu3);

        jMenuRelatorios.setText("Relatórios");
        jMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatoriosActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Todos Empréstimos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem5);

        jMenuItem2.setText("Ferramentas e Gastos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem2);

        jMenuItem6.setText("Ranking de Empréstimos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem6);

        jMenuBar2.add(jMenuRelatorios);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCadastroAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroAmigoActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroAmigo objeto = new CadastroAmigo();
        objeto.setVisible(true);
    }//GEN-LAST:event_jCadastroAmigoActionPerformed

    private void jCadastroFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroFerramentaActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroFerramenta objeto = new CadastroFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_jCadastroFerramentaActionPerformed

    private void jCadastroEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroEmprestimosActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroEmprestimo objeto = new CadastroEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_jCadastroEmprestimosActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        //Encerra o programa
        System.exit(0);

    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jGerenciarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGerenciarAmigoActionPerformed
        // TODO add your handling code here:
        GerenciamentoAmigo objeto = new GerenciamentoAmigo();
        objeto.setVisible(true);

    }//GEN-LAST:event_jGerenciarAmigoActionPerformed

    private void jGerenciarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGerenciarFerramentaActionPerformed
        // TODO add your handling code here:
        GerenciamentoFerramenta objeto = new GerenciamentoFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_jGerenciarFerramentaActionPerformed

    private void jGerenciarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGerenciarEmprestimoActionPerformed
        // TODO add your handling code here:
        GerenciamentoEmprestimo objeto = new GerenciamentoEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_jGerenciarEmprestimoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        RelatorioEmprestimo objeto = new RelatorioEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRelatoriosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        RelatorioRankingEmprestimo objeto = new RelatorioRankingEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        RelatorioGastoFerramenta objeto = new RelatorioGastoFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadastroAmigo;
    private javax.swing.JMenuItem jCadastroEmprestimos;
    private javax.swing.JMenuItem jCadastroFerramenta;
    private javax.swing.JMenuItem jGerenciarAmigo;
    private javax.swing.JMenuItem jGerenciarEmprestimo;
    private javax.swing.JMenuItem jGerenciarFerramenta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenuItem jMenuSair;
    // End of variables declaration//GEN-END:variables
}
